name: Automated Documentation Updater

on:
  schedule:
    - cron: "*/2 * * * *"

  workflow_dispatch:

jobs:

  update-docs:

    runs-on: ubuntu-latest

    steps:

      # Step 1 - Download AI repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 - Install Python
      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: '3.11'

      # Step 3 - Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4 - Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "AI Documentation Bot"
          git config --global user.email "bot@example.com"

      # Step 5 - Clone target repository
      - name: Clone Target Repository
        run: |
          git clone https://github.com/Sakshibhoyar16/agentic-test-repo.git

      # Step 6 - Run AI Documentation Maintainer
      - name: Run AI Documentation Maintainer

        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TARGET_REPO_PATH: ./agentic-test-repo

        run: |
          python main.py

      # Step 7 - Commit and Push Documentation
      - name: Commit and Push Documentation

        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

        run: |
          cd agentic-test-repo

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/Sakshibhoyar16/agentic-test-repo.git

          git add .

          git commit -m "AI updated documentation" || echo "No changes to commit"

          git push
